apiVersion : apps/v1
kind: Deployment
metadata:
  name: nodehello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodehello
  template:
    metadata:
      labels:
        app: nodehello
    spec:
      containers:
        - name: nodecc24
          image: nodecc24.azurecr.io/nodeh:latest
          ports:
          - containerPort: 8000